/* SPDX-License-Identifier: GPL-2.0 */
#ifndef LUNA_ISOLATION_PROTOCOL_H
#define LUNA_ISOLATION_PROTOCOL_H

#include <sel4/sel4.h>

#define LUNA_ISOLATION_CHILD_IMAGE "luna-lkl-task"
#define LUNA_ISOLATION_SECRET        ((seL4_Word)0x4c554e4153454352ULL)
#define LUNA_LKL_THREAD_SLOTS        63
#define LUNA_TIMER_SLOT              63
#define LUNA_CONSOLE_SLOT            64
#define LUNA_RESOURCE_SLOTS          65
#define LUNA_RESOURCE_STACK_PAGES    64
#define LUNA_RESOURCE_TLS_VALUE      ((seL4_Word)0x4c4b4c544c53504fULL)
#define LUNA_SYNC_SLOTS              128
#define LUNA_RESTART_STRESS_ROUNDS   100
#define LUNA_CHILD_HEAP_BASE          0x20000000UL
#define LUNA_CHILD_HEAP_SIZE          (32UL * 1024UL * 1024UL)
#define LUNA_CHILD_HEAP_PAGES         (LUNA_CHILD_HEAP_SIZE / 4096UL)
#define LUNA_PERSISTENT_DISK_SIZE      (16UL * 1024UL * 1024UL)
#define LUNA_PERSISTENT_DISK_PAGE_BITS 21UL
#define LUNA_PERSISTENT_DISK_PAGES     \
    (LUNA_PERSISTENT_DISK_SIZE / (1UL << LUNA_PERSISTENT_DISK_PAGE_BITS))
#define LUNA_DISK_IO_BASE              0x24000000UL
#define LUNA_DISK_IO_SIZE              (64UL * 1024UL)
#define LUNA_DISK_IO_PAGES             (LUNA_DISK_IO_SIZE / 4096UL)
#define LUNA_PERSISTENT_MARKER         "luna-phase-2.3-persistent\n"

enum luna_isolation_mode {
    LUNA_ISOLATION_MODE_FAULT = 1,
    LUNA_ISOLATION_MODE_CLEAN = 2,
    LUNA_ISOLATION_MODE_STRESS = 3,
};

enum luna_isolation_event {
    LUNA_ISOLATION_EVENT_READY = 0x100,
    LUNA_ISOLATION_EVENT_DONE = 0x101,
    LUNA_ISOLATION_EVENT_LKL_LINKED = 0x102,
    LUNA_ISOLATION_EVENT_RESOURCE_OK = 0x103,
    LUNA_ISOLATION_EVENT_LKL_INIT_OK = 0x104,
    LUNA_ISOLATION_EVENT_RESOURCE_CONFIGURED = 0x105,
    LUNA_ISOLATION_EVENT_LKL_BOOT_OK = 0x106,
    LUNA_ISOLATION_EVENT_LKL_HALT_OK = 0x107,
    LUNA_ISOLATION_EVENT_LKL_SHELL_READY = 0x108,
    LUNA_ISOLATION_EVENT_ALLOCATOR_OK = 0x109,
    LUNA_ISOLATION_EVENT_ALLOCATOR_RELEASED = 0x10a,
    LUNA_ISOLATION_EVENT_SYNC_TLS_OK = 0x10b,
    LUNA_ISOLATION_EVENT_THREAD_TIMER_OK = 0x10c,
    LUNA_ISOLATION_EVENT_VIRTIO_BLOCK_OK = 0x10d,
    LUNA_ISOLATION_EVENT_USER_PROGRAM_OK = 0x10e,
    LUNA_ISOLATION_EVENT_MEMORY_MAP = 0x200,
    LUNA_ISOLATION_EVENT_MEMORY_UNMAP = 0x201,
    LUNA_ISOLATION_EVENT_DISK_READ = 0x202,
    LUNA_ISOLATION_EVENT_DISK_WRITE = 0x203,
    LUNA_ISOLATION_EVENT_DISK_FLUSH = 0x204,
    LUNA_ISOLATION_EVENT_PRIVATE_PAGE_VISIBLE = 0x1ff,
};

enum luna_manager_command {
    LUNA_COMMAND_CONFIGURE_SLOT = 1,
    LUNA_COMMAND_CONFIGURE_SYNC = 2,
    LUNA_COMMAND_CONFIGURE_CONSOLE = 3,
    LUNA_COMMAND_START = 4,
    LUNA_COMMAND_MEMORY_RESULT = 5,
    LUNA_COMMAND_CONFIGURE_DISK = 6,
    LUNA_COMMAND_DISK_RESULT = 7,
};

#endif /* LUNA_ISOLATION_PROTOCOL_H */
